FROM nginx:alpine

RUN apk add --no-cache tzdata

COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html /tmp/index.html

RUN BUILD_TIME=$(TZ=Europe/Stockholm date '+%d %B %Y kl. %H:%M CET') && \
    sed "s|__BUILD_TIMESTAMP__|$BUILD_TIME|g" /tmp/index.html > /usr/share/nginx/html/index.html && \
    rm /tmp/index.html

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
