FROM golang:1.23-alpine AS builder

WORKDIR /build

COPY go.mod main.go ./

RUN go mod download && \
    go mod tidy && \
    CGO_ENABLED=0 GOOS=linux go build -o guestbook-api .

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /build/guestbook-api .

EXPOSE 8080

CMD ["./guestbook-api"]
